### ISSUE TITLE
Template name does not appear on mobile 

### ISSUE THREAD

**Issue by brimwats** [bramses/obsidian-stack-overflow#2]
I have a template called "person template" and another called "person automove template" but it is not possible to distinguish between the two. ideally I'd be able to know which one I was applying 

![Screenshot_20220601-113317_Obsidian](https://user-images.githubusercontent.com/73113656/171477575-69253c2d-39f2-4cbe-afc8-bb27a3997722.jpg)

**Comment by bramses** [comment]
Hi @brimwats thanks for the issue, unfortunately I'm a bit confused:

> I have a template called "person template" and another called "person automove template" but it is not possible to distinguish between the two. ideally I'd be able to know which one I was applying

are you looking for the functionality from https://github.com/zolrath/obsidian-auto-link-title?

**Comment by brimwats** [comment]
ah, so sorry! wrong repository entirely
