### ISSUE TITLE
Use the StackExchange API rather than parsing the HTML?

### ISSUE THREAD

**Issue by 0xdevalias** [bramses/obsidian-stack-overflow#6]
I noticed that currently the plugin fetches the URL, then parses the HTML to extract the content. I was wondering if it might be more robust to make use of the StackExchange API instead?

- https://api.stackexchange.com/docs
- https://api.stackexchange.com/docs/authentication
- https://api.stackexchange.com/docs/throttle

Based on a quick skim of the pages, I believe you would need to get a `key` for the application, but you could probably skip the authentication aspects per-user (which the 'throttle' page says would just lead to it using a shared quota per IP/key):

> Applications should be registered on [Stack Apps](http://stackapps.com/apps/oauth/register) to get a request key. Request keys grant more requests per day, and are necessary for using access_tokens created via [authentication](https://api.stackexchange.com/docs/authentication).

> If an application does not have an `access_token`, then the application shares an IP based quota with all other applications on that IP. This quota is based on the key being passed by the applications; it is the max of the daily request limit for the applications involved, which by default is 10,000. This quota scheme is essentially unchanged from earlier versions of the API.

You would then be able to use endpoints such as:

- https://api.stackexchange.com/docs/questions-by-ids
- https://api.stackexchange.com/docs/answers-on-questions
- https://api.stackexchange.com/docs/answers-by-ids
- etc

By changing the default filter used, you can get more/less information returned in each request. Of particular note, questions/answers have a `body` and `body_markdown` key that can be included:

- https://api.stackexchange.com/docs/types/question
- https://api.stackexchange.com/docs/types/answer

A basic example can be seen here:

- https://api.stackexchange.com/docs/answers-on-questions#order=desc&sort=activity&ids=61907922&filter=!nKzQURFm*e&site=stackoverflow&run=true

Which generates an API request URL like the following:

- https://api.stackexchange.com/2.3/questions/61907922/answers?order=desc&sort=activity&site=stackoverflow&filter=!nKzQURFm*e

By passing the different subdomain values for other stackexchange sites in the `site` key, it would be possible to support more than just StackOverflow, which seems to be a limitation in the current code (see https://github.com/bramses/obsidian-stack-overflow/issues/7)

**Comment by bramses** [comment]
This is super well thought out, thank you for the work! That is a pretty breaking change though so it would have to be a major version upgrade -- I currently don't have the bandwith to tackle this, so I'm gonna close this for now, but if the app ever has a 2.0 release, I'll look into it!! (feel free to fork/PR ofc as well)

**Comment by 0xdevalias** [comment]
Totally understand that, and appreciate the effort you've put in so far :)
